services:
  db2:
    image: icr.io/db2_community/db2
    platform: linux/amd64
    container_name: db2-migration-demo
    privileged: true
    ports:
      - "50000:50000"
      - "55000:55000"
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: db2inst1-pwd
      DB2INSTANCE: db2inst1
      DBNAME: ICWADB
      BLU: false
      ENABLE_ORACLE_COMPATIBILITY: false
      ARCHIVE_LOGS: false
      AUTOCONFIG: false
    volumes:
      - db2-data:/database
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - db2-network
    healthcheck:
      test: ["CMD", "su", "-", "db2inst1", "-c", "db2 connect to ICWADB"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  migrations:
    build:
      context: ../
      dockerfile: docker/Dockerfile.migrations
    container_name: db2-migrations
    platform: linux/amd64
    environment:
      DB2__Host: db2
      DB2__Port: 50000
      DB2__Database: ICWADB
      DB2__Username: db2inst1
      DB2__Password: db2inst1-pwd
    networks:
      - db2-network
    depends_on:
      db2:
        condition: service_healthy
    profiles:
      - migrations

volumes:
  db2-data:
    driver: local

networks:
  db2-network:
    driver: bridge