CREATE TABLE RISKS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RISK_NAME VARCHAR(50) NOT NULL,
    RISK_DESCRIPTION VARCHAR(1000),
    RISK_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RISK_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);