-- V13__Create_multi_schema_example.sql
-- Example of managing multiple schemas in one migration

-- Create REPORTING schema if not exists
-- Note: DB2 doesn't support IF NOT EXISTS, so we handle with error handling
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' 
    BEGIN END;
  
  EXECUTE IMMEDIATE 'CREATE SCHEMA REPORTING';
END;

-- Create AUDIT schema
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' 
    BEGIN END;
  
  EXECUTE IMMEDIATE 'CREATE SCHEMA AUDIT';
END;

-- Create table in REPORTING schema
CREATE TABLE REPORTING.POLICY_SUMMARY (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    REPORT_DATE DATE NOT NULL,
    TOTAL_POLICIES INTEGER,
    TOTAL_CLAIMS INTEGER,
    TOTAL_AMOUNT DECIMAL(15,2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create table in AUDIT schema
CREATE TABLE AUDIT.MIGRATION_LOG (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SCHEMA_NAME VARCHAR(50),
    TABLE_NAME VARCHAR(100),
    ACTION VARCHAR(50),
    PERFORMED_BY VARCHAR(100),
    PERFORMED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create cross-schema view
CREATE VIEW REPORTING.ACTIVE_POLICIES AS
SELECT 
    p.ID,
    p.POLICY_NUMBER,
    ph.POLICYHOLDER_NAME,
    p.PREMIUM_AMOUNT
FROM DB2INST1.POLICIES p
JOIN DB2INST1.POLICYHOLDERS ph ON p.POLICYHOLDER_ID = ph.ID
WHERE p.STATUS = 'Active';

-- Log this migration in audit schema
INSERT INTO AUDIT.MIGRATION_LOG (SCHEMA_NAME, TABLE_NAME, ACTION, PERFORMED_BY)
VALUES 
    ('REPORTING', 'POLICY_SUMMARY', 'CREATE TABLE', 'Flyway'),
    ('AUDIT', 'MIGRATION_LOG', 'CREATE TABLE', 'Flyway'),
    ('REPORTING', 'ACTIVE_POLICIES', 'CREATE VIEW', 'Flyway');