-- V1__Create_policyholders_table.sql
CREATE TABLE POLICYHOLDERS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    POLICYHOLDER_CODE VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255),
    PHONE VARCHAR(50),
    ADDRESS VARCHAR(500),
    DATE_OF_BIRTH DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MIGRATED_FROM_CUSTOMER_ID INTEGER
);