-- V2__Create_policies_table.sql
CREATE TABLE POLICIES (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    POLICY_NUMBER VARCHAR(50) NOT NULL,
    POLICYHOLDER_ID INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    PREMIUM_AMOUNT DECIMAL(10,2),
    COVERAGE_AMOUNT DECIMAL(12,2),
    DEDUCTIBLE DECIMAL(10,2),
    START_DATE DATE,
    END_DATE DATE,
    STATUS VARCHAR(50) DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (POLICYHOLDER_ID) REFERENCES POLICYHOLDERS(ID)
);