-- V3__Create_claims_table.sql
CREATE TABLE CLAIMS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLAIM_NUMBER VARCHAR(50) NOT NULL,
    POLICY_ID INTEGER NOT NULL,
    CLAIM_DATE DATE,
    DESCRIPTION VARCHAR(1000),
    CLAIM_AMOUNT DECIMAL(10,2),
    STATUS VARCHAR(50) DEFAULT 'PENDING',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (POLICY_ID) REFERENCES POLICIES(ID)
);