CREATE TABLE APPS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APP_NAME VARCHAR(50) NOT NULL,
    APP_DESCRIPTION VARCHAR(1000),
    APP_URL VARCHAR(255),
    APP_ICON VARCHAR(255),
    APP_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    APP_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);