CREATE TABLE STAFF (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    STAFF_NAME VARCHAR(50) NOT NULL,
    STAFF_EMAIL VARCHAR(255),
    STAFF_PHONE VARCHAR(50),
    STAFF_ADDRESS VARCHAR(500),
    STAFF_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STAFF_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);